### ISSUE TITLE
Question about "afterlastconstraint" in SingleAgentAStar_Solver

### ISSUE THREAD

**Issue by losecanvas** [J-morag/MAPF#87]
Hello, I have some questions about this part. Do you mean that if there is no constraint or the constraint time is exceeded, there is no need for the agent to perform waiting actions, so there is no need to put the current point into the node to be extended. If so, is it also not necessary to add the current point to the node to be extended in the initopen method?

**Comment by J-morag** [comment]
Hello losecanvas,

`afterLastConstraint` means the state is past the time of the last **change** in constraints. So, from that point onward, there are either no constraints at all, or they are all infinite. You are correct - when this is true, there is no need to perform waiting actions.
This condition cannot be added to `initOpen`, because an empty plan, where the agent starts on its target, it still represented by a single stay move, so we need to generate that even if there are no constraints. I guess this means we generate an unnecessary state when there are no constraints, but it shouldn't affect correctness. The successors of that extra state would be thrown away as duplicates of the move actions generated in `initOpen` anyway.

I hope this helps clear things up. If you have further questions, feel free to ask.

**Comment by losecanvas** [comment]
Thank you for your reply, which has helped me solve the problem! Also, do you have a personal email address? In this way, it will be more convenient for me to communicate with you when I have some questions in the future.

________________________________
发件人: ***@***.*** ***@***.***> 代表 J-morag ***@***.***>
发送时间: 2024年4月8日 10:00
收件人: J-morag/MAPF ***@***.***>
抄送: losecanvas ***@***.***>; Author ***@***.***>
主题: Re: [J-morag/MAPF] Question about "afterlastconstraint" in SingleAgentAStar_Solver (Issue #87)


Hello losecanvas,

afterLastConstraint means the state is past the time of the last change in constraints. So, from that point onward, there are either no constraints at all, or they are all infinite. You are correct - when this is true, there is no need to perform waiting actions.
This condition cannot be added to initOpen, because an empty plan, where the agent starts on its target, it still represented by a single stay move, so we need to generate that even if there are no constraints. I guess this means we generate an unnecessary state when there are no constraints, but it shouldn't affect correctness. The successors of that extra state would be thrown away as duplicates of the move actions generated in initOpen anyway.

I hope this helps clear things up. If you have further questions, feel free to ask.

―
