### ISSUE TITLE
questions about SingleAgentAStarSIPP_Solver

### ISSUE THREAD

**Issue by Leechang831** [J-morag/MAPF#97]
In the MAPF problem, a single robot can move in four directions or wait in place, resulting in five possible states. The SIPP algorithm is known for its optimality and completeness. To ensure these properties, theoretically, all possible move and wait states should be expanded when generating nodes. However, in the `moveInSafeInterval` function, you check whether the agent can enter the next node within the safe interval and, if not, whether it meets the conditions to wait at the current location. In such cases, a wait node is generated along with a child node for moving to the next node. However, only the latter is added to the open list. Does this approach fail to cover the full search space required by SIPP, potentially compromising its optimality and completeness?

**Comment by J-morag** [comment]
Hello @Leechang831 ,

Thank you for your question. In SIPP, generating child states for waiting in place is not needed, since all valid 'wait' options are compressed into a single state with an 'interval'. That is where the speedup comes from in SIPP.
We individually check different times where we can wait within the interval, because we also have to make sure the specific edge we take for traversing into the next interval is safe at the specific time when we traverse it. This information is not expressed by the intervals.

Let me know if you have further questions on the topic.
